name: cosmic_vision
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^11.2.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.0.10
  google_fonts: ^6.1.0
  image_gallery_saver_plus: ^3.0.5
  intl: ^0.20.2
  lottie: ^3.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

